name: Snyk Open Source Test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'main'

jobs:
  open-source-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v3

        - name: Build with Gradle
          run: ./gradlew build

        - name: Test Open Source Dependencies with Snyk
          uses: snyk/actions/gradle-jdk17@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            command: test
            args: --all-projects --exclude=pip-sample